project:
  type: website
  output-dir: docs
resources:
  - Rory_Mulhern_CV.pdf
website:
  title: "Mysite"
  favicon: images/favicon2.png
  navbar:
    fixed: true
    background: primary
    search: false
    title: false
    logo: images/favicon2.png
    right:
      - icon: person-lines-fill
        href: about.qmd
        text: About Me
      - icon: journal-bookmark-fill
        href: projects.qmd
        text: Projects
      - icon: camera-reels
        href: Media.qmd
        text: Media
      - href: Untitled-1.qmd
        text: Quarto Test
  sidebar:
     contents:
      - href: berlin.qmd
        text: "BIP Berlin, Germany ğŸ‡©ğŸ‡ª"
      - href: rag.qmd
        text: "RAG Society ğŸ’¶"
      - href: vermont.qmd
        text: "SG-FECC Burlington ğŸ‡ºğŸ‡¸"
      - href: tutorials.qmd
        text: "Teaching Tutorials ğŸ“š"
      - href: business_strategy.qmd
        text: "Business Strategy ğŸ‘”"
      - href: econometrics_model.qmd
        text: "Econometrics ğŸ“ˆ"
      - href: pythonml.qmd
        text: "ML & Python ğŸ"
      - href: NED.qmd
        text: "NED â˜•ï¸"
      - href: data_project.qmd
        text: "Visualistion ğŸ“Š"
      - href: sustainability.qmd
        text: "Sustainability ğŸŒ"


        

format:
  html:
    theme:
      light: 
      - lux
      - style.scss
    mainfont: Afacad Flux
    page-layout: full
    css: 
      - styles.css
      - style.scss
    toc: false



